### ISSUE TITLE
Return None Type error after extrude mesh

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/geometry-script#2]
I am testing this script:

```python
from geometry_script import *

@tree("Blah")

def myblah(geometry: Geometry):
    #p = cube().subdivision_surface(level=2).extrude_mesh() # ERROR this one does not work wonder why; after extrude, the shade
    p = cube().subdivision_surface(level=2)
    return p.set_shade_smooth(shadeSmooth = 1, mesh=Geometry)
```

Can you help with this one?

**Comment by enzyme69** [comment]
I think I might figure out something:

<img width="1032" alt="Screenshot 2022-12-05 at 12 03 06 am" src="https://user-images.githubusercontent.com/3952687/205492039-34a1db7f-973c-4f94-b752-9dc1fe2548d2.png">

**Comment by carson-katri** [comment]
You need to return `p.extrude_mesh().mesh` because it has multiple outputs. It doesn’t know if you want to return the mesh, top or side output.

**Comment by enzyme69** [comment]
Roger that! Thanks Carson~

from geometry_script import *

@tree("Blah")

```python
def myblah(geometry: Geometry):
    #p = cube().subdivision_surface(level=2).extrude_mesh() # this one does not work wonder why
    p = cube().subdivision_surface(level=2).merge_by_distance(distance = 0.2).extrude_mesh().mesh
    return p.set_shade_smooth(mesh = Geometry)
```

**Comment by carson-katri** [comment]
```python
p.set_shade_smooth(mesh = Geometry)
```
FYI, this is almost correct but you do not need the `mesh=Geometry` part. When you run `set_shade_smooth` on `p`, it is automatically passing `p` in for the `mesh` argument. And `Geometry` with a capital `G` refers to the type not a specific set of Geometry.

```Python
# two possible ways of using this:
p.set_shade_smooth()
set_shade_smooth(mesh=p)
```
