### ISSUE TITLE
Simulation Input not create geometry socket

### ISSUE THREAD

**Issue by zNightlord** [carson-katri/geometry-script#24]
![image](https://github.com/carson-katri/geometry-script/assets/61040487/ec3a5a92-1bca-4cb1-a33d-3c2f6eaae8f5)

**Comment by zNightlord** [comment]
In [Simulation Zone Pair Commit](https://projects.blender.org/blender/blender/commit/98bc439e4759bdd1c9c3a6fa41671a6fa39e4099) 

node.py at L183 
```
# Simulation input must be paired with the output.
       input_node.pair_with_output(output_node)
```

**Comment by jusu** [comment]
You could pair simulation in and out with something like:

`diff -r /Users/jusu/Desktop/geometry-script-main/api/node_mapper.py ./api/node_mapper.py
17a18
> 
76c77
<             return list(outputs.values())[0]
---
>             return list(outputs.values())[0], node
78c79
<             return OutputsList(outputs)
---
>             return OutputsList(outputs), node
330c331
<   
---
> 
Only in ./api/static: __pycache__
diff -r /Users/jusu/Desktop/geometry-script-main/api/static/simulation.py ./api/static/simulation.py
16c16
<         simulation_in = simulation_input(geometry=geometry)
---
>         simulation_in, in_node = simulation_input(geometry=geometry)
24,25c24,27
<         return simulation_output(geometry=block(simulation_in.geometry, *args, **kwargs)).geometry
<     return wrapped
\ No newline at end of file
---
>         simulation_out, out_node = simulation_output(geometry=block(simulation_in.geometry, *args, **kwargs))
>         in_node.pair_with_output(out_node)
>         return simulation_out.geometry
>     return wrapped`

This connects in <-> out, but socket connections to simulation_in don't seem to be made. Sorry, too quickly scanning the code to make more progress right now. Nice api!

**Comment by carson-katri** [comment]
@zNightlord I've update the API for Blender 3.6: https://github.com/carson-katri/geometry-script/pull/28

Let me know if you have any problems with this revision.
