### ISSUE TITLE
Programatically specify the input group behaviour at the modifier panel

### ISSUE THREAD

**Issue by rsaccon** [carson-katri/geometry-script#38]
When directly editing nodes, there is the Group Input Panel to specify Input Default, Min, Max and more, see screenshot below. But with Geometry Script what I have found out so far, only Default can be set. Is there a way to programatically set the other fields from that panel ? For numbers it would be great to be able to specify Min and Max 

![Screenshot 2023-11-17 at 03 36 39](https://github.com/carson-katri/geometry-script/assets/16122/61b0731c-207d-4b9c-89e2-cd06a3b80aea)

**Comment by carson-katri** [comment]
An implementation was started, but not completed here: https://github.com/carson-katri/geometry-script/blob/da99654edbed2dc18379955d93694c58dc62379c/api/types.py#L35-L39

It would allow you to write something like this:
```python
def min_max_demo(value: Int[slice(0, 1)]):
    pass
```

It's just a matter of completing the implementation.

**Comment by carson-katri** [comment]
The API should probably be extended to support more options:

```python
def test(value: Int[0, 1]): pass # min, max
def test(value: Int["My Value"]): pass # custom input name
def test(value: Int[InputOptions(min=0, max=1, tooltip="The value you want", ...)]): pass # full-featured configuration
```

Alternatively, wrapper types could be used. I find this is a bit more confusing though:

```python
def test(value: MinMax[Int, 0, 1]): pass
def test(value: Named[Int, "My Value"]): pass
def test(value: Tooltip[MinMax[Int, 0, 1], "The value you want"]): pass
```

**Comment by rsaccon** [comment]
Great, thanks, so this will be coming eventually ...

**Comment by rsaccon** [comment]
I started looking at the source code, in order to try to complete the implementation. But I have a question regarding the missing parts of the implementation. I see at several places  in the code base that a value gets assigned to the `default_value` attribute of an input node. Now I assume at those places also `start` and `stop` attributes need to be set for min and max. And the same or similar for custom input name, tooltip, etc. Does that make sense ?

**Comment by rsaccon** [comment]
Got one microstep further in understanding things. Could not find any attributes at he output sockets of the input group which suggest they serve to set `min` and `max`.  These are the attributes for an example input socket I played with (as learning exercise for later actually setting the options via geometry script):
```
['__doc__', '__module__', '__slots__', 'bl_idname', 'bl_label', 'bl_rna', 'bl_subtype_label', 'default_value', 'description', 'display_shape', 'draw', 'draw_color', 'enabled', 'hide', 'hide_value', 'identifier', 'is_linked', 'is_multi_input', 'is_output', 'is_unavailable', 'label', 'link_limit', 'name', 'node', 'rna_type', 'show_expanded', 'type']
```
I can set visually in the UI things like `default`,  `bl_subtype_label` and I can retrieve those those attributes in Python by walking the node tree and checking the links between the nodes. But there is nothing there for setting `min` and `max`. Anything obvious I am missing ?

**Comment by BradyAJohnston** [comment]
@rsaccon the min and max have to be set via the `interface.items_tree` for the node group, and not the output sockets for the `Group Input`.

```python
node_group = bpy.data.nodes['my_node']
node_group.interface.items_tree["Value"].default_value = 1
node_group.interface.items_tree["Value"].min_value = 1
node_group.interface.items_tree["Value"].max_value = 0
```

**Comment by rsaccon** [comment]
@BradyAJohnston That really helped. Thanks a lot.

**Comment by rsaccon** [comment]
After trying to halfway understand what is going on under the hood at Geometry Script, I managed to implement min and max input options at my fork. The API looks like this right now:
```Python
 # min
def test(value: Int[0]): pass
def test(value: Float[0.0]): pass

# min, max
def test(value: Int[0, 1]): pass
def test(value: Float[0.0, 1.0]): pass

# min, max (slice notation)
def test(value: Int[0:1]): pass
def test(value: Float[0.0:1.0]): pass
```
Before making a PR I want to test some more edge cases and properly handle them.  And extend with an `InputOption` class to allow additional input options (subtype, custom-name, tooltip and hide-in-modifier).

**Comment by rsaccon** [comment]
Now I got stuck with trying to set the input subtype (such as Distance, Percentage, etc). While it is straight forward to set name, default, min, max and tooltip just by setting the proper input socket attribute, for the subtype it seems an operator needs to be called (just setting the attribute only changes the selector label but not the value). If I do it by hand in the Node UI, then this shows up in the console log:
```
bpy.ops.node.tree_socket_change_subtype(socket_subtype='DISTANCE')
```
so I try to do it programmatically in the console and it fails:
```Python
>>> bpy.ops.node.tree_socket_change_subtype(socket_subtype='DISTANCE')
...
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Applications/Blender36.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.node.tree_socket_change_subtype.poll() failed, context is incorrect
```

next I try set the context. After taking a look at the node input options UI source code, I come up with another failed attempt:
```
>>> active_socket = bpy.data.node_groups['example'].inputs[0]
>>> context_override = bpy.context.copy()
>>> context_override["interface_socket"] = active_socket
>>> with bpy.context.temp_override(**context_override):
...     bpy.ops.node.tree_socket_change_subtype(socket_subtype='DISTANCE')
... 
Traceback (most recent call last):
  File "<blender_console>", line 2, in <module>
  File "/Applications/Blender36.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.node.tree_socket_change_subtype.poll() failed, context is incorrect
```

So how do I set the right context ??? The second attempt failed because there is no `interface_socket` in `bpy.context`. But what context do I have to set ? Or is there a different way to set programmatically the input subtype ?

**Comment by rsaccon** [comment]
My suggested solution for this issue is in this [PR](https://github.com/carson-katri/geometry-script/pull/46), so closing this.
