### ISSUE TITLE
Trouble with join_geometry()

### ISSUE THREAD

**Issue by rsaccon** [carson-katri/geometry-script#39]
I feel stupid about this, it just doesn't work fo me on Blender 3.6 (using an older Geometric Script which does work on Blender 3.6)

Union with `mesh_boolean()` works fine (but I don't need to check for intersections)

`yield` also works fine, see my example below
```Python
@tree("experiment")
def experiment():  # OK
    yield cube().mesh
    yield cylinder().mesh.transform_geometry(translation=combine_xyz(
        x=2
    ))
```

but when I try to do the same (I think) with `join_geometry()`
```Python
@tree("experiment")
def experiment():  # NOT OK
    return join_geometry([
        cube().mesh,
        cylinder().mesh.transform_geometry(translation=combine_xyz(
            x=2
        ))
    ])
```
I get an error:
![Screenshot 2023-11-17 at 12 16 54](https://github.com/carson-katri/geometry-script/assets/16122/9bfa8717-e107-4849-b9dc-9fba81af4206)
(Sorry for the screenshot, but somehow Blender 3.6 on Mac does not allow me to copy-paste the stacktrace from the Python Texteditor, probably I should adapt my workflow to start Blender from the command line, then errors show up there)

**Comment by carson-katri** [comment]
It should be:
```python
join_geometry(geometry=[mesh1, mesh2])
```

**Comment by alphadito** [comment]
[Adding](https://carson-katri.github.io/geometry-script/setup/external-editing.html) the typeshed folder to your module look up paths is super helpful to determine which keyword arguments are needed for each node.

or you can just ctrl-f on this file.
`<geometry-script-root>/typeshed/geometry_script.py`

**Comment by rsaccon** [comment]
OMG, of course it cannot work with the wrong signature! Thanks a lot to both of you, gonna closing it.
