### ISSUE TITLE
How to inspect node group output values via python

### ISSUE THREAD

**Issue by rsaccon** [carson-katri/geometry-script#43]
My Geometry Script creates some extra data (beside Geometry) at the Group Output. In the visual node editor one can just hover over the field to inspect it, see screenshot for an example float value:
![Screenshot 2023-11-26 at 03 54 00](https://github.com/carson-katri/geometry-script/assets/16122/1ece31e1-6d32-4882-95c2-34651d5a2c99)
Does anybody know a way to access this value directly in Python (in a way like we can do it for Group Input values) ?

The only way I am aware of is anything else than direct: instead of storing the value in the Group Output, it gets stored as named attribute, then it can be visually inspected in the Geometry Nodes spreadsheet area or in Python: the active object can be evaluated and the resulting mesh data will contain the names attributes. For exporting large amount of data form Geometry nodes, I think this approach makes sense, but for just a few values, I would prefer to use non-Geometry Group Output values.

**Comment by alphadito** [comment]
Hmm... it looks like the [string](https://github.com/blender/blender/blob/46131a681341d359e66de7d5f542af186ca54bfb/source/blender/editors/space_node/node_draw.cc#L1273C1-L1274C1) displayed by the node socket tooltip in the node editor UI comes from a [GeoModifierLog](https://github.com/blender/blender/blob/01a2bd03695f217616acc2581fe8746f5cd226d7/source/blender/nodes/NOD_geometry_nodes_log.hh#L344) which is called by [node_draw](https://github.com/blender/blender/blob/46131a681341d359e66de7d5f542af186ca54bfb/source/blender/editors/space_node/node_draw.cc#L1555-L1556C1). Unfortunately, I don't think the Geometry Node logging functionality is exposed through the python api.

**Comment by rsaccon** [comment]
Thanks a lot for the detailed info. So it looks like there is no easy-and-straight-frorward way to access the outputs. I will try the complicated way with the named attributes and see how that goes.
