### ISSUE TITLE
Cylinder: expected float, get FloatDistance

### ISSUE THREAD

**Issue by SanBingYouYong** [carson-katri/geometry-script#44]
Following the doc and typeshed, we should provide `FloatDistance` as input sockets to `cylinder` node, but in runtime it gives the following error: 

`Python: Traceback (most recent call last):
  File ".../temp.blend/building_mass.py", line 9, in <module>
  File ".../blender/3.2/scripts/addons/geometry-script-main/api/tree.py", line 136, in build_tree
    outputs = builder(**builder_inputs)
  File ".../temp.blend/building_mass.py", line 12, in building_mass_cylindrical
  File ".../blender/3.2/scripts/addons/geometry-script-main/api/node_mapper.py", line 56, in build
    setattr(node, prop.identifier, value)
TypeError: bpy_struct: item.attr = val: GeometryNodeMeshCylinder.height expected a float type, not FloatDistance`

The code: 

    @gs.tree("Test Cylinder")
    def test_cylinder(radius: gs.FloatDistance, height: gs.FloatDistance):
        return gs.cylinder(radius=radius, height=height)

I also tried making it a `Float`, but does not work either. 

It seems `cylinder` expects a plain float type, but I can't, as designed, read the float value from this socket. Is this due to a version mismatch?

**Comment by rsaccon** [comment]
Can you not just convert it to `float` ? I mean, it just works in the most simple case of using a numeric `float` value for the `radius` and `depth` (in blender 3.6, seems Geometry Nodes api is changing all the time).

**Comment by SanBingYouYong** [comment]
I tried, `float(radius)` does not work as the most intuitive solution here. I can't seem to find a detailed doc for things like `FloatDistance`

**Comment by rsaccon** [comment]
Something like this seems to work for me (but not as expected):
```Python
from geometry_script import *

@tree("experiment")
def test_cylinder(radius: FloatDistance = 2.0):
    return cylinder(
        radius=radius
    ).mesh
```
I would expect that `FloatDistance` means that the value has to be  `>= 0.0`, but in the modifier UI panel I can move the radius slider into negative values.

**Comment by SanBingYouYong** [comment]
> Ah this is because `height` is actually an inherited property of the parent class `bpy.types.GeometryNode` (perhaps related to how the node is drawn in the editor?). `depth` might be the argument you're looking for which is a node input of `bpy.types.GeometryNodeMeshCylinder`.

:rofl: Yes this is indeed the case, `depth` is also what shows up as parameters, my bad.

**Comment by SanBingYouYong** [comment]
> About your question regarding documentation about FloatDistance, the best I found is just a look at the Input option panel: ![Screenshot 2023-12-02 at 23 51 17](https://private-user-images.githubusercontent.com/16122/287486836-d45b3bd3-1e75-4c38-8e17-5d94314530bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTgzNTcsIm5iZiI6MTcwMTU5ODA1NywicGF0aCI6Ii8xNjEyMi8yODc0ODY4MzYtZDQ1YjNiZDMtMWU3NS00YzM4LThlMTctNWQ5NDMxNDUzMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEwMDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZmE0MzU1Mjk4ZDg5ODQ0NDA4M2JlZjUzOWY1NTI1ZTI2ZmFiYjlkZmY2OGY4M2NjZTc5MjBmNjJlODEwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJFz69tHZadtA-1Uthefzfyo-nZ7kwQADLBfOHee9yE) So FloatDistance is just a float with subtype Distance (so the values show up with the length unit). While in the real world a distance is never negative, in 3d modelling it might make sense, eg. extrusion in direction of negative axis.

Blender 3.2 does not seem to have `subtype`, I guess that's a version difference. But yeah this approach does look reasonable in finding out what's needed, thanks!
