### ISSUE TITLE
Getting "Python: Traceback (most recent call last):   File "C:\... .py", line 4, in <module>   File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\tree.py", line 39, in build_tree      AttributeError: 'GeometryNodeTree' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by TheOtherRealm** [carson-katri/geometry-script#47]
In Blender 4.0.2, I am getting:
```
Python: Traceback (most recent call last):
  File "C:\Develop\oshoe\Public\RightInsoleGeometry2023-12-18-1615.blend\insoleRightGeometryScript.py", line 4, in <module>
  File "C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\tree.py", line 39, in build_tree
    
AttributeError: 'GeometryNodeTree' object has no attribute 'inputs'
```
When I try to run anything, for example:
```
from geometry_script import *
@tree("Cube Tree")
def cube_tree(size: Vector = (1, 1, 1)):
    return cube(size=size)
```
This code runs in v3.6
OS: Windows 10 Enterprise 

There does not appear to be anything in the `C:\Users\Someone\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\typeshed` folder.  Which is probably the culprit, but why the files were not generated in the install process I am not sure. 

I uninstalled and re-installed the extension to no avail.

**Comment by carson-katri** [comment]
Looks like the add-on folder is called `geometry-script-main`. Can you try renaming it to `geometry_script`? That could be causing the issue.

**Comment by TheOtherRealm** [comment]
Never mind, I just needed to uninstall 👉 ***RESTART*** 👉 Reinstall
It may be a good idea to mention this somewhere in the installation process that if you are upgrading instead of fresh install, you need to uninstall and restart before you install the new version.
