### ISSUE TITLE
Instance On Points: Rotation shows degrees but method accepts radians

### ISSUE THREAD

**Issue by SanBingYouYong** [carson-katri/geometry-script#48]
Not sure if this is caused by Blender version too old (3.2 where it does not have subtype for Float and Vector stuff), but: 
 - `Instance On Points` node's rotation socket accepts angles in degrees: 
![rotation in degrees](https://github.com/carson-katri/geometry-script/assets/54278583/17bd3cc5-82bd-434b-94cf-ef47a39db4f5)
 - its Geometry Scripts method `instance_on_points` seems to interpret rotation values as radians: 
![code](https://github.com/carson-katri/geometry-script/assets/54278583/bc27b8a6-dc50-4290-8c0f-304e389779ff)
![node](https://github.com/carson-katri/geometry-script/assets/54278583/5e2f062d-91b2-4b78-a3e9-fada2bff6213)
![visual](https://github.com/carson-katri/geometry-script/assets/54278583/ae8632e3-4ce6-4843-91e5-f64084234de6)

Maybe there is a hidden default conversion from radians to angles in the code to node conversion process.

**Comment by alphadito** [comment]
This appears to be just a quirk of the UI https://projects.blender.org/blender/blender/issues/81389.  You can change the rotation scene units to radians in the properties editor which affects the input that's directly typed into the node but linked vector inputs will always be in radians.

**Comment by SanBingYouYong** [comment]
Thanks!
