### ISSUE TITLE
call a node group

### ISSUE THREAD

**Issue by cqcsir** [carson-katri/geometry-script#6]
Is it possible to call a node group generated in blender in python ?

**Comment by carson-katri** [comment]
It should be possible with the `group` function:

```python
group(node_tree=bpy.data.node_groups["Some Group Name"], some_input=5)
```

**Comment by cqcsir** [comment]
I'm sorry, I'm not clear. What I mean is that can I use the node group generated by blender as a @tree method and call it in geometries-script?

**Comment by carson-katri** [comment]
I think that code snippet above would do that. So if you created a node group in Blender’s geometry node editor called “Some Group Name”, you could then use it in a Geometry Script with that `group` function.

If that doesn’t seem like what you’re looking for, can you provide some example code of what you would expect it to work like?

**Comment by cqcsir** [comment]
amazing!!   thx~~

**Comment by cqcsir** [comment]
> I think that code snippet above would do that. So if you created a node group in Blender’s geometry node editor called “Some Group Name”, you could then use it in a Geometry Script with that `group` function.
> 
> If that doesn’t seem like what you’re looking for, can you provide some example code of what you would expect it to work like?

Thank you very much. Your above tips are exactly what I want, and my doubts have been eliminated. Thank you again!

**Comment by carson-katri** [comment]
Great! Glad you got it working.
