### ISSUE TITLE
set value of a curve

### ISSUE THREAD

**Issue by cqcsir** [carson-katri/geometry-script#7]
Can I set the value of a curve for a node of this type in python?
![image](https://user-images.githubusercontent.com/19362788/210158505-90f66532-4e47-470f-bb39-ac167e3bbea9.png)

**Comment by carson-katri** [comment]
I've added curve support with the following API (see #10):

```python
float_curve(
    mapping=Curve(
        Point(0, 0),
        Point(0.5, 0.25),
        Point(1, 1, HandleType.VECTOR), # Optionally specify a handle type, such as `AUTO`, `VECTOR`, or `AUTO_CLAMPED`.
    )
)
```

**Comment by cqcsir** [comment]
wow, with this API, it's getting easier and easier
